### ISSUE TITLE
Fetch failed

### ISSUE THREAD

**Issue by andrex4k** [alonbl/ovirt-overlay#8]
I think it is necessary to update ebuilds
/var/calculate/tmp/portage/app-emulation/otopi-1.2.1/temp/build.log:
http://pastebin.calculate-linux.ru/ru/show/11810
/var/calculate/tmp/portage/dev-java/quartz-bin-2.1.7/temp/build.log:
http://pastebin.calculate-linux.ru/ru/show/11811
- app-emulation/otopi [1]
   Available versions:  ~1.1.4 ~1.2.0 (~)1.2.1 **9999 {java ELIBC="FreeBSD" PYTHON_TARGETS="python2_7 python3_3 python3_4"}
   Homepage:            http://www.ovirt.org
   Description:         oVirt Task Oriented Pluggable Installer/Implementation
  
  dev-java/quartz-bin [1]
     Available versions:  (4) (~)2.1.7
       {doc ELIBC="FreeBSD"}
     Homepage:            http://quartz-scheduler.org/
     Description:         Enterprise Job Scheduler

on the website of the version is already newer and in mirrors old isn't present

**Comment by alonbl** [comment]
This overlay is no longer supported, due to many binary dependencies added
to this project.

**Comment by andrex4k** [comment]
thanks for the answer) I will try to think up something
